name: Build and Deploy Documentation

on:
  push:
  pull_request:

jobs:
  build-documentation:
    name: Build and deploy cFS documents
    uses: ./.github/workflows/build-deploy-doc.yml
    with:
      target: "[\"fm-usersguide\"]"
      app-name: fm
      buildpdf: ${{ github.event_name == 'push' && contains(github.ref, 'main')}}
      deploy: ${{ github.event_name == 'push' && contains(github.ref, 'main')}}
